---
languageCode: en-us
permalinks:
  blog: /blog/:title/
pluralizelisttitles: "false"
enableEmoji: true
related:
  includeNewer: true
  indices:
    - name: keywords # The name of the indice, same as Front Matter's .Param key.
      weight: 100
    - name: categories # The name of the indice, same as Front Matter's .Param key.
      weight: 20

...
